export interface SectionDef {
  key: string;
  label: string;
  defaultOrder: number;
}

export const TEMPLATE_SECTIONS: Record<string, SectionDef[]> = {
  barbershop: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "services", label: "Servicios",                 defaultOrder: 2 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 3 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 4 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 5 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 6 },
  ],
  gym: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "classes",  label: "Nuestras Clases",           defaultOrder: 2 },
    { key: "trainers", label: "Entrenadores",              defaultOrder: 3 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 4 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 5 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 6 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 7 },
  ],
  salon: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "services", label: "Servicios",                 defaultOrder: 2 },
    { key: "team",     label: "Nuestro Equipo",            defaultOrder: 3 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 4 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 5 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 6 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 7 },
  ],
  hardware: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "products", label: "Catalogo de Productos",     defaultOrder: 2 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 3 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 4 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 5 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 6 },
  ],
  restaurant: [
    { key: "header",  label: "Encabezado (nav)",          defaultOrder: 0 },
    { key: "hero",    label: "Banner principal",           defaultOrder: 1 },
    { key: "menu",    label: "Nuestro Menu",               defaultOrder: 2 },
    { key: "booking", label: "Reservas",                   defaultOrder: 3 },
    { key: "contact", label: "Contacto",                   defaultOrder: 4 },
    { key: "blocks",  label: "Bloques del constructor",    defaultOrder: 5 },
    { key: "footer",  label: "Pie de pagina",              defaultOrder: 6 },
  ],
  generic: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "services", label: "Servicios",                 defaultOrder: 2 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 3 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 4 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 5 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 6 },
  ],
  clinic: [
    { key: "header",      label: "Encabezado (nav)",      defaultOrder: 0 },
    { key: "hero",        label: "Banner principal",       defaultOrder: 1 },
    { key: "specialties", label: "Especialidades",         defaultOrder: 2 },
    { key: "team",        label: "Equipo Medico",          defaultOrder: 3 },
    { key: "office",      label: "Info del Consultorio",   defaultOrder: 4 },
    { key: "booking",     label: "Citas",                  defaultOrder: 5 },
    { key: "blocks",      label: "Bloques del constructor",defaultOrder: 6 },
    { key: "footer",      label: "Pie de pagina",          defaultOrder: 7 },
  ],
  school: [
    { key: "header",      label: "Encabezado (nav)",      defaultOrder: 0 },
    { key: "hero",        label: "Banner principal",       defaultOrder: 1 },
    { key: "courses",     label: "Cursos",                 defaultOrder: 2 },
    { key: "instructors", label: "Instructores",           defaultOrder: 3 },
    { key: "benefits",    label: "Por que elegirnos",      defaultOrder: 4 },
    { key: "booking",     label: "Inscripciones",          defaultOrder: 5 },
    { key: "contact",     label: "Contacto",               defaultOrder: 6 },
    { key: "blocks",      label: "Bloques del constructor",defaultOrder: 7 },
    { key: "footer",      label: "Pie de pagina",          defaultOrder: 8 },
  ],
  veterinary: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "services", label: "Servicios",                 defaultOrder: 2 },
    { key: "staff",    label: "Nuestro Equipo",            defaultOrder: 3 },
    { key: "booking",  label: "Reservas",                  defaultOrder: 4 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 5 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 6 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 7 },
  ],
  lawyer: [
    { key: "header",   label: "Encabezado (nav)",         defaultOrder: 0 },
    { key: "hero",     label: "Banner principal",          defaultOrder: 1 },
    { key: "areas",    label: "Areas de Practica",         defaultOrder: 2 },
    { key: "team",     label: "Nuestro Equipo",            defaultOrder: 3 },
    { key: "office",   label: "Informacion del Estudio",   defaultOrder: 4 },
    { key: "booking",  label: "Consultas",                 defaultOrder: 5 },
    { key: "contact",  label: "Contacto",                  defaultOrder: 6 },
    { key: "blocks",   label: "Bloques del constructor",   defaultOrder: 7 },
    { key: "footer",   label: "Pie de pagina",             defaultOrder: 8 },
  ],
  realestate: [
    { key: "header",     label: "Encabezado (nav)",       defaultOrder: 0 },
    { key: "hero",       label: "Banner principal",        defaultOrder: 1 },
    { key: "properties", label: "Propiedades",             defaultOrder: 2 },
    { key: "advisors",   label: "Asesores",                defaultOrder: 3 },
    { key: "services",   label: "Servicios",               defaultOrder: 4 },
    { key: "booking",    label: "Consultas",               defaultOrder: 5 },
    { key: "contact",    label: "Contacto",                defaultOrder: 6 },
    { key: "blocks",     label: "Bloques del constructor", defaultOrder: 7 },
    { key: "footer",     label: "Pie de pagina",           defaultOrder: 8 },
  ],
  hotel: [
    { key: "header",     label: "Encabezado (nav)",       defaultOrder: 0 },
    { key: "hero",       label: "Banner principal",        defaultOrder: 1 },
    { key: "rooms",      label: "Habitaciones",            defaultOrder: 2 },
    { key: "amenities",  label: "Servicios y Amenidades",  defaultOrder: 3 },
    { key: "extra",      label: "Informacion Adicional",   defaultOrder: 4 },
    { key: "booking",    label: "Reservas",                defaultOrder: 5 },
    { key: "contact",    label: "Contacto",                defaultOrder: 6 },
    { key: "blocks",     label: "Bloques del constructor", defaultOrder: 7 },
    { key: "footer",     label: "Pie de pagina",           defaultOrder: 8 },
  ],
};
